[build]
   base = "web_app/"
   publish = "dist/webApp/"

[context.master]
   command = "ng build --prod"

[context.dev]
   command = "ng build"

[[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200

[[headers]] 
   for = "/ngsw-worker.js"
   [headers.values]
      cache-control = "max-age=0,no-cache,no-store,must-revalidate"

