export interface ICountry {
	name: string;
	countryCode: number;
}

export const COUNTRIES: ICountry[] = [
	{ name: 'Afghanistan', countryCode: 4 },
	{ name: 'Åland Islands', countryCode: 248 },
	{ name: 'Albania', countryCode: 8 },
	{ name: 'Algeria', countryCode: 12 },
	{ name: 'American Samoa', countryCode: 16 },
	{ name: 'Andorra', countryCode: 20 },
	{ name: 'Angola', countryCode: 24 },
	{ name: 'Anguilla', countryCode: 660 },
	{ name: 'Antarctica', countryCode: 10 },
	{ name: 'Antigua and Barbuda', countryCode: 28 },
	{ name: 'Argentina', countryCode: 32 },
	{ name: 'Armenia', countryCode: 51 },
	{ name: 'Aruba', countryCode: 533 },
	{ name: 'Australia', countryCode: 36 },
	{ name: 'Austria', countryCode: 40 },
	{ name: 'Azerbaijan', countryCode: 31 },
	{ name: 'Bahamas', countryCode: 44 },
	{ name: 'Bahrain', countryCode: 48 },
	{ name: 'Bangladesh', countryCode: 50 },
	{ name: 'Barbados', countryCode: 52 },
	{ name: 'Belarus', countryCode: 112 },
	{ name: 'Belgium', countryCode: 56 },
	{ name: 'Belize', countryCode: 84 },
	{ name: 'Benin', countryCode: 204 },
	{ name: 'Bermuda', countryCode: 60 },
	{ name: 'Bhutan', countryCode: 64 },
	{ name: 'Bolivia (Plurinational State of)', countryCode: 68 },
	{ name: 'Bonaire, Sint Eustatius and Saba', countryCode: 535 },
	{ name: 'Bosnia and Herzegovina', countryCode: 70 },
	{ name: 'Botswana', countryCode: 72 },
	{ name: 'Bouvet Island', countryCode: 74 },
	{ name: 'Brazil', countryCode: 76 },
	{ name: 'British Indian Ocean Territory', countryCode: 86 },
	{ name: 'Brunei Darussalam', countryCode: 96 },
	{ name: 'Bulgaria', countryCode: 100 },
	{ name: 'Burkina Faso', countryCode: 854 },
	{ name: 'Burundi', countryCode: 108 },
	{ name: 'Cabo Verde', countryCode: 132 },
	{ name: 'Cambodia', countryCode: 116 },
	{ name: 'Cameroon', countryCode: 120 },
	{ name: 'Canada', countryCode: 124 },
	{ name: 'Cayman Islands', countryCode: 136 },
	{ name: 'Central African Republic', countryCode: 140 },
	{ name: 'Chad', countryCode: 148 },
	{ name: 'Chile', countryCode: 152 },
	{ name: 'China', countryCode: 156 },
	{ name: 'Christmas Island', countryCode: 162 },
	{ name: 'Cocos (Keeling) Islands', countryCode: 166 },
	{ name: 'Colombia', countryCode: 170 },
	{ name: 'Comoros', countryCode: 174 },
	{ name: 'Congo', countryCode: 178 },
	{ name: 'Congo, Democratic Republic of the', countryCode: 180 },
	{ name: 'Cook Islands', countryCode: 184 },
	{ name: 'Costa Rica', countryCode: 188 },
	{ name: "Côte d'Ivoire", countryCode: 384 },
	{ name: 'Croatia', countryCode: 191 },
	{ name: 'Cuba', countryCode: 192 },
	{ name: 'Curaçao', countryCode: 531 },
	{ name: 'Cyprus', countryCode: 196 },
	{ name: 'Czechia', countryCode: 203 },
	{ name: 'Denmark', countryCode: 208 },
	{ name: 'Djibouti', countryCode: 262 },
	{ name: 'Dominica', countryCode: 212 },
	{ name: 'Dominican Republic', countryCode: 214 },
	{ name: 'Ecuador', countryCode: 218 },
	{ name: 'Egypt', countryCode: 818 },
	{ name: 'El Salvador', countryCode: 222 },
	{ name: 'Equatorial Guinea', countryCode: 226 },
	{ name: 'Eritrea', countryCode: 232 },
	{ name: 'Estonia', countryCode: 233 },
	{ name: 'Eswatini', countryCode: 748 },
	{ name: 'Ethiopia', countryCode: 231 },
	{ name: 'Falkland Islands (Malvinas)', countryCode: 238 },
	{ name: 'Faroe Islands', countryCode: 234 },
	{ name: 'Fiji', countryCode: 242 },
	{ name: 'Finland', countryCode: 246 },
	{ name: 'France', countryCode: 250 },
	{ name: 'French Guiana', countryCode: 254 },
	{ name: 'French Polynesia', countryCode: 258 },
	{ name: 'French Southern Territories', countryCode: 260 },
	{ name: 'Gabon', countryCode: 266 },
	{ name: 'Gambia', countryCode: 270 },
	{ name: 'Georgia', countryCode: 268 },
	{ name: 'Germany', countryCode: 276 },
	{ name: 'Ghana', countryCode: 288 },
	{ name: 'Gibraltar', countryCode: 292 },
	{ name: 'Greece', countryCode: 300 },
	{ name: 'Greenland', countryCode: 304 },
	{ name: 'Grenada', countryCode: 308 },
	{ name: 'Guadeloupe', countryCode: 312 },
	{ name: 'Guam', countryCode: 316 },
	{ name: 'Guatemala', countryCode: 320 },
	{ name: 'Guernsey', countryCode: 831 },
	{ name: 'Guinea', countryCode: 324 },
	{ name: 'Guinea-Bissau', countryCode: 624 },
	{ name: 'Guyana', countryCode: 328 },
	{ name: 'Haiti', countryCode: 332 },
	{ name: 'Heard Island and McDonald Islands', countryCode: 334 },
	{ name: 'Holy See', countryCode: 336 },
	{ name: 'Honduras', countryCode: 340 },
	{ name: 'Hong Kong', countryCode: 344 },
	{ name: 'Hungary', countryCode: 348 },
	{ name: 'Iceland', countryCode: 352 },
	{ name: 'India', countryCode: 356 },
	{ name: 'Indonesia', countryCode: 360 },
	{ name: 'Iran (Islamic Republic of)', countryCode: 364 },
	{ name: 'Iraq', countryCode: 368 },
	{ name: 'Ireland', countryCode: 372 },
	{ name: 'Isle of Man', countryCode: 833 },
	{ name: 'Israel', countryCode: 376 },
	{ name: 'Italy', countryCode: 380 },
	{ name: 'Jamaica', countryCode: 388 },
	{ name: 'Japan', countryCode: 392 },
	{ name: 'Jersey', countryCode: 832 },
	{ name: 'Jordan', countryCode: 400 },
	{ name: 'Kazakhstan', countryCode: 398 },
	{ name: 'Kenya', countryCode: 404 },
	{ name: 'Kiribati', countryCode: 296 },
	{ name: "Korea (Democratic People's Republic of)", countryCode: 408 },
	{ name: 'Korea, Republic of', countryCode: 410 },
	{ name: 'Kuwait', countryCode: 414 },
	{ name: 'Kyrgyzstan', countryCode: 417 },
	{ name: "Lao People's Democratic Republic", countryCode: 418 },
	{ name: 'Latvia', countryCode: 428 },
	{ name: 'Lebanon', countryCode: 422 },
	{ name: 'Lesotho', countryCode: 426 },
	{ name: 'Liberia', countryCode: 430 },
	{ name: 'Libya', countryCode: 434 },
	{ name: 'Liechtenstein', countryCode: 438 },
	{ name: 'Lithuania', countryCode: 440 },
	{ name: 'Luxembourg', countryCode: 442 },
	{ name: 'Macao', countryCode: 446 },
	{ name: 'Madagascar', countryCode: 450 },
	{ name: 'Malawi', countryCode: 454 },
	{ name: 'Malaysia', countryCode: 458 },
	{ name: 'Maldives', countryCode: 462 },
	{ name: 'Mali', countryCode: 466 },
	{ name: 'Malta', countryCode: 470 },
	{ name: 'Marshall Islands', countryCode: 584 },
	{ name: 'Martinique', countryCode: 474 },
	{ name: 'Mauritania', countryCode: 478 },
	{ name: 'Mauritius', countryCode: 480 },
	{ name: 'Mayotte', countryCode: 175 },
	{ name: 'Mexico', countryCode: 484 },
	{ name: 'Micronesia (Federated States of)', countryCode: 583 },
	{ name: 'Moldova, Republic of', countryCode: 498 },
	{ name: 'Monaco', countryCode: 492 },
	{ name: 'Mongolia', countryCode: 496 },
	{ name: 'Montenegro', countryCode: 499 },
	{ name: 'Montserrat', countryCode: 500 },
	{ name: 'Morocco', countryCode: 504 },
	{ name: 'Mozambique', countryCode: 508 },
	{ name: 'Myanmar', countryCode: 104 },
	{ name: 'Namibia', countryCode: 516 },
	{ name: 'Nauru', countryCode: 520 },
	{ name: 'Nepal', countryCode: 524 },
	{ name: 'Netherlands', countryCode: 528 },
	{ name: 'New Caledonia', countryCode: 540 },
	{ name: 'New Zealand', countryCode: 554 },
	{ name: 'Nicaragua', countryCode: 558 },
	{ name: 'Niger', countryCode: 562 },
	{ name: 'Nigeria', countryCode: 566 },
	{ name: 'Niue', countryCode: 570 },
	{ name: 'Norfolk Island', countryCode: 574 },
	{ name: 'North Macedonia', countryCode: 807 },
	{ name: 'Northern Mariana Islands', countryCode: 580 },
	{ name: 'Norway', countryCode: 578 },
	{ name: 'Oman', countryCode: 512 },
	{ name: 'Pakistan', countryCode: 586 },
	{ name: 'Palau', countryCode: 585 },
	{ name: 'Palestine, State of', countryCode: 275 },
	{ name: 'Panama', countryCode: 591 },
	{ name: 'Papua New Guinea', countryCode: 598 },
	{ name: 'Paraguay', countryCode: 600 },
	{ name: 'Peru', countryCode: 604 },
	{ name: 'Philippines', countryCode: 608 },
	{ name: 'Pitcairn', countryCode: 612 },
	{ name: 'Poland', countryCode: 616 },
	{ name: 'Portugal', countryCode: 620 },
	{ name: 'Puerto Rico', countryCode: 630 },
	{ name: 'Qatar', countryCode: 634 },
	{ name: 'Réunion', countryCode: 638 },
	{ name: 'Romania', countryCode: 642 },
	{ name: 'Russian Federation', countryCode: 643 },
	{ name: 'Rwanda', countryCode: 646 },
	{ name: 'Saint Barthélemy', countryCode: 652 },
	{ name: 'Saint Helena, Ascension and Tristan da Cunha', countryCode: 654 },
	{ name: 'Saint Kitts and Nevis', countryCode: 659 },
	{ name: 'Saint Lucia', countryCode: 662 },
	{ name: 'Saint Martin (French part)', countryCode: 663 },
	{ name: 'Saint Pierre and Miquelon', countryCode: 666 },
	{ name: 'Saint Vincent and the Grenadines', countryCode: 670 },
	{ name: 'Samoa', countryCode: 882 },
	{ name: 'San Marino', countryCode: 674 },
	{ name: 'Sao Tome and Principe', countryCode: 678 },
	{ name: 'Saudi Arabia', countryCode: 682 },
	{ name: 'Senegal', countryCode: 686 },
	{ name: 'Serbia', countryCode: 688 },
	{ name: 'Seychelles', countryCode: 690 },
	{ name: 'Sierra Leone', countryCode: 694 },
	{ name: 'Singapore', countryCode: 702 },
	{ name: 'Sint Maarten (Dutch part)', countryCode: 534 },
	{ name: 'Slovakia', countryCode: 703 },
	{ name: 'Slovenia', countryCode: 705 },
	{ name: 'Solomon Islands', countryCode: 90 },
	{ name: 'Somalia', countryCode: 706 },
	{ name: 'South Africa', countryCode: 710 },
	{ name: 'South Georgia and the South Sandwich Islands', countryCode: 239 },
	{ name: 'South Sudan', countryCode: 728 },
	{ name: 'Spain', countryCode: 724 },
	{ name: 'Sri Lanka', countryCode: 144 },
	{ name: 'Sudan', countryCode: 729 },
	{ name: 'Suriname', countryCode: 740 },
	{ name: 'Svalbard and Jan Mayen', countryCode: 744 },
	{ name: 'Sweden', countryCode: 752 },
	{ name: 'Switzerland', countryCode: 756 },
	{ name: 'Syrian Arab Republic', countryCode: 760 },
	{ name: 'Taiwan, Province of China', countryCode: 158 },
	{ name: 'Tajikistan', countryCode: 762 },
	{ name: 'Tanzania, United Republic of', countryCode: 834 },
	{ name: 'Thailand', countryCode: 764 },
	{ name: 'Timor-Leste', countryCode: 626 },
	{ name: 'Togo', countryCode: 768 },
	{ name: 'Tokelau', countryCode: 772 },
	{ name: 'Tonga', countryCode: 776 },
	{ name: 'Trinidad and Tobago', countryCode: 780 },
	{ name: 'Tunisia', countryCode: 788 },
	{ name: 'Turkey', countryCode: 792 },
	{ name: 'Turkmenistan', countryCode: 795 },
	{ name: 'Turks and Caicos Islands', countryCode: 796 },
	{ name: 'Tuvalu', countryCode: 798 },
	{ name: 'Uganda', countryCode: 800 },
	{ name: 'Ukraine', countryCode: 804 },
	{ name: 'United Arab Emirates', countryCode: 784 },
	{
		name: 'United Kingdom of Great Britain and Northern Ireland',
		countryCode: 826,
	},
	{ name: 'United States of America', countryCode: 840 },
	{ name: 'United States Minor Outlying Islands', countryCode: 581 },
	{ name: 'Uruguay', countryCode: 858 },
	{ name: 'Uzbekistan', countryCode: 860 },
	{ name: 'Vanuatu', countryCode: 548 },
	{ name: 'Venezuela (Bolivarian Republic of)', countryCode: 862 },
	{ name: 'Viet Nam', countryCode: 704 },
	{ name: 'Virgin Islands (British)', countryCode: 92 },
	{ name: 'Virgin Islands (U.S.)', countryCode: 850 },
	{ name: 'Wallis and Futuna', countryCode: 876 },
	{ name: 'Western Sahara', countryCode: 732 },
	{ name: 'Yemen', countryCode: 887 },
	{ name: 'Zambia', countryCode: 894 },
	{ name: 'Zimbabwe', countryCode: 716 },
];
